builds:
  - binary: monero-exporter
    main: ./cmd/monero-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    tags:
      - osusergo
      - netgo
      - static_build
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
