apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://xps.utxo.com.br:9090
    isDefault: true
    version: 1
    editable: false
    timeInterval: 30s
