---
services:
  grafana:
    command:
    - -config=/etc/grafana/grafana.ini
    container_name: grafana
    image: index.docker.io/utxobr/monero-exporter-grafana@sha256:eb06f3451432e26ce17e78283ced2814952fdf715cae9916bc9584f283a92078
    ports:
    - 3000:3000
    volumes:
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    - ./grafana/provisioning:/etc/grafana/provisioning:ro
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
  monero-exporter:
    command:
    - --monero-addr=http://127.0.0.1:18081
    container_name: monero-exporter
    image: index.docker.io/utxobr/monero-exporter@sha256:98f5d68a9c8a2cb92c0d981845d9ddc691c86e98318aa89e88a7d9646750a2c8
    network_mode: service:monerod
  monerod:
    command:
    - --check-updates=disabled
    - --data-dir=/data
    - --enforce-dns-checkpointing
    - --limit-rate=999999
    - --no-igd
    - --no-zmq
    - --out-peers=32
    - --p2p-bind-ip=127.0.0.1
    - --p2p-bind-port=18080
    - --rpc-bind-ip=127.0.0.1
    - --rpc-bind-port=18081
    - --rpc-restricted-bind-ip=0.0.0.0
    - --rpc-restricted-bind-port=18089
    container_name: monerod
    image: index.docker.io/utxobr/monero-exporter-monerod@sha256:f5b6d355ab09b5372434dfacef21421407166c0b4e5c742ae8e57bfd194c53c0
    ports:
    - 18080:18080
    - 18089:18089
    volumes:
    - monerod-data:/data
  prometheus:
    command:
    - --config.file=/etc/prometheus/config.yaml
    - --storage.tsdb.path=/data
    - --storage.tsdb.retention.time=30d
    container_name: prometheus
    image: index.docker.io/utxobr/monero-exporter-prometheus@sha256:ff7bad10b24e26dec5d51211071dd05efbd2bd92bcd10dbb1882ded3ce36af73
    volumes:
    - prometheus-data:/data
    - ./prometheus/config.yaml:/etc/prometheus/config.yaml:ro
version: "3"
volumes:
  monerod-data: null
  prometheus-data: null
